# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            KSEG - Key Software Engineering Guidelines
tagline:          'KSEG'
description:      ''
url:              rafaelromao.github.io/KSEG
baseurl:          /kseg/

author:
  name:           'Rafael Romão'
  url:            github.com/rafaelromao

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/rafaelromao/KSEG
